server:
  error:
    include-stacktrace: ON_PARAM
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/client_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    baseline-on-migrate: true
    enable: true
    schemas: public
    url: jdbc:postgresql://localhost:5432/client_db
    user: postgres
    password: postgres
    locations: classpath:db/migration
    baseline-description: "init"
    baseline-version: 0
api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}